server:
  port: 7070
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LuisAlbertoQ/Projecto_Integrador.git
          searchPaths: config-data
          #username:
          #password:
          default-label: jhoel
  security:
    user:
      name: root
      password: 123456