server:
  port: 82




eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost




spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-notificaciones-service
          uri: lb://ms-notificaciones-service
          predicates:
            - Path=/notificacion/**
        - id: ms-documentos-service
          uri: lb://ms-documentos-service
          predicates:
            - Path=/documento/**